### ISSUE TITLE
No Site

### ISSUE THREAD

**Issue by Irrelevant1114** [vanillinarchives/vanillinarchives.github.io#3]
When trying the link to open the website, it opens to another page with a link to itself and the name "vanillin_archives".

Code:
<!DOCTYPE>
<html lang="en-US"><head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<title>vanillin_archive | vanillinarchives.github.io</title>
<meta name="generator" content="Jekyll v3.9.2">
<meta property="og:title" content="vanillin_archive">
<meta property="og:locale" content="en_US">
<link rel="canonical" href="https://vanillinarchives.github.io/">
<meta property="og:url" content="https://vanillinarchives.github.io/">
<meta property="og:site_name" content="vanillinarchives.github.io">
<meta property="og:type" content="website">
<meta name="twitter:card" content="summary">
<meta property="twitter:title" content="vanillin_archive">
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebSite","headline":"vanillin_archive","name":"vanillinarchives.github.io","url":"https://vanillinarchives.github.io/"}</script>

    <link rel="stylesheet" href="/assets/css/style.css?v=e53a714dca41f3a984a15fbab6f148f36d8b7c9c">
    

  </head>
  <body data-new-gr-c-s-check-loaded="14.1130.0" data-gr-ext-installed="">
    <div class="container-lg px-3 my-5 markdown-body">
      
      <h1><a href="https://vanillinarchives.github.io/">vanillinarchives.github.io</a></h1>
      

      <h1 id="vanillin_archive">vanillin_archive</h1>

      
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.0/anchor.min.js" integrity="sha256-lZaRhKri35AyJSypXXs4o6OPFTbTmUoltBbDCbdzegg=" crossorigin="anonymous"></script>
    <script>anchors.add();</script>
  

</body><grammarly-desktop-integration data-grammarly-shadow-root="true"></grammarly-desktop-integration></html>

**Comment by vanilla5751** [comment]
look at discussions to find new site link
